### ISSUE TITLE
Fix functionality of Item Attribute Put Request 

### ISSUE THREAD

**Issue by ogicodes** [ejkorol/recipe-book#14]
currently due to the type validation in `IItemAttribute` the Item Attribute put request is expecting the user to provide both `name` and `description` so if only one is provided the put request returns an error. 

in order for the put request to have dynamic functionality we want to be able to input one or both fields but not require both both and only update the one that was input.

**Comment by ejkorol** [comment]
### Migrating Schemas and Routes
---

Since we are migrating the models and all routes, i'll close this issue as we wont need the `put` requests moving forward :)
