### ISSUE TITLE
Create API Routes, Handlers, and Service for Biome Model

### ISSUE THREAD

**Issue by ejkorol** [ejkorol/recipe-book#21]
#### The goal is to implement three GET routes:

1. Get All Biomes: Fetches a list of all biomes
2. Get Biome by ID: Fetches a specific biome by its ID
3. Search Biomes: Searches biomes based on a query parameter

---

#### API Routes:

1. GET `/api/biomes`: Retrieves all biomes
2. GET `/api/biomes/:id`: Retrieves a biome by its ID
3. GET `/api/biomes/search`: Searches for biomes based on a query parameter (e.g., by name or description)

#### Controllers:
_(Following the same patterns as `food` controller)_

1. `getAllBiomes`: Handles the request to get all biomes
2. `getBiomeById`: Handles the request to get a biome by its ID
3. `searchBiomes`: Handles the request to search biomes based on a query parameter

#### Services:
_(Follow the same pattern as `food` service)_

#### API Route Implementation:

1. Set up the routes in seperate file
2. Integrate route into `./src/routes/index.ts`

#### Additional Notes:

Ensure that all error cases are handled properly
Structure the code in a consistent way

**Comment by ejkorol** [comment]
Ensure to prefix the branch to submit the PR with `feat-<#TICKET>`  (｡◕‿‿◕｡)

**Comment by ogicodes** [comment]
done and dusted. out of this world!  @ejkorol
