### ISSUE TITLE
Create API Routes, Handlers, and Service for Entity Model

### ISSUE THREAD

**Issue by ejkorol** [ejkorol/recipe-book#22]
### The goal is to implement three GET routes:

1. **Get All Entities**: Fetches a list of all entities.
2. **Get Entity by ID**: Fetches a specific entity by its ID.
3. **Search Entities**: Searches entities based on a query parameter.

---

### API Routes:

1. **GET `/api/entities`**: Retrieves all entities.
2. **GET `/api/entities/:id`**: Retrieves an entity by its ID.
3. **GET `/api/entities/search`**: Searches for entities based on a query parameter (e.g., by name or description).

### Controllers:
_(Following the same patterns as `food` controller)_

1. **`getAllEntities`**: Handles the request to get all entities.
2. **`getEntityById`**: Handles the request to get an entity by its ID.
3. **`searchEntities`**: Handles the request to search entities based on a query parameter.

### Services:
_(Follow the same pattern as `food` service)_

1. **`getAllEntitiesService`**: Service function to fetch all entities from the database.
2. **`getEntityByIdService`**: Service function to fetch an entity by its ID.
3. **`searchEntitiesService`**: Service function to search entities based on a query parameter.

### API Route Implementation:

1. **Set up the routes** in a separate file.
2. **Integrate the route** into `./src/routes/index.ts`.

### Additional Notes:

- Ensure that all error cases are handled properly.
- Structure the code in a consistent way.

**Comment by ogicodes** [comment]
closing ticket, routes have been created and merged to dev
